### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ikdekker** [ikdekker/bsc-smart-contract-research#4]
deadlines:
  - [x] 15/3 about two pages written
  - [x] 22/3 complete draft of the paper
  - [x] 28/3 review peer paper
  - [x] 11/4 submit final literature report to supervisor & BrightSpace
  - [x] 18/4 presentation 
  - [x] 18/4 online peer review of group members

**Comment by ikdekker** [comment]
Intermediate (soft) deadline: tuesday 12/3 see [this issue](https://github.com/ikdekker/bsc-smart-contract-research/issues/6)

**Comment by ikdekker** [comment]
I'd like to have finished most content of the presentation on 16/4 so each individual member can study it. Then we can practice together on 17/4. I'll work on a first version of a powerpoint soon.

**Comment by ikdekker** [comment]
As per: https://github.com/Tribler/tribler/issues/4239

This will be closed
